### PR TITLE
Define ACL_TABLE and ACL_RULE table in STATE_DB

### PR DESCRIPTION
**Pull request by bingwang-ms**
This PR is to add two macro definition to support a new STATE_DB schema.
HLD https://github.com/sonic-net/SONiC/pull/1261

### CODE REVIEW

**Review by ZhaohuiS — DISMISSED** [review]
LGTM

**Review by ZhaohuiS — APPROVED** [review]

**Comment by StormLiangMS** [comment]
@bingwang-ms could you help to raise PR for 202211?

**Comment by bingwang-ms** [comment]
PR created for `202211` branch. https://github.com/sonic-net/sonic-swss-common/pull/770

**Pull request merged**
