### PR TITLE
[Logrotate] Add log rotate configuration tables

### PR DESCRIPTION
**Pull request by fastiuk**
Add names for LOGGING configuration table

### CODE REVIEW

**Review by dgsudharsan — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@fastiuk please handle conflict so I can help and merge

**Comment by prgeor** [comment]
@fastiuk @liat-grozovik can we have the HLD please?

**Comment by liat-grozovik** [comment]
@prsunny can you please approve?

**Comment by fastiuk** [comment]
@prgeor please approve, and merge.
This is incredibly simple changes, just one line, but 3 PRs depends on it.

**Comment by fastiuk** [comment]
@prgeor please approve, and merge.
This is incredibly simple changes, just one line, but 3 PRs depends on it.

**Review by saiarcot895 — APPROVED** [review]

**Comment by wen587** [comment]
Hi @fastiuk , could you help add LOGGING Yang model?

**Pull request merged**
