### PR TITLE
Add more information when connect redis fail

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**Why I did this?**

Make it clear that why redis connect fail

**How I did this?**

Add error message and error code when redis connection failed

**How I verify this?**

Manual test
sonic-mgmt regression

### CODE REVIEW

**Review by stephenxs — APPROVED** [review]

**Review by dgsudharsan — APPROVED** [review]

**Comment by Junchao-Mellanox** [comment]
Hi @prsunny , could you please review and merge?

**Comment by liat-grozovik** [comment]
@qiluo-msft could you please help to review or suggest another reviewer?

**Review by liat-grozovik — APPROVED** [review]

**Comment by bingwang-ms** [comment]
@qiluo-msft Can you please help review?

**Comment by bingwang-ms** [comment]
@qiluo-msft Kindly remind. Can you help review?

**Pull request merged**
