### PR TITLE
[Ci] Fix collect log error in azp template

### PR DESCRIPTION
**Pull request by xumia**
Fix collect log error in azp template

### CODE REVIEW

**Comment by StormLiangMS** [comment]
@xumia do we need this in 202305?

**Comment by xumia** [comment]
> @xumia do we need this in 202305?

Added the request, thanks.

**Comment by developfast** [comment]
Can this be included in 202012 asap too?

**Comment by liuh-80** [comment]
Change been manually cherry-pick to 202012 by this: https://github.com/sonic-net/sonic-swss-common/pull/800

**Comment by StormLiangMS** [comment]
@xumia do we have an ADO for this?

**Pull request merged**
