### PR TITLE
[schema] Add SAG table for static anycast gateway

### PR DESCRIPTION
**Pull request by superchild**
Add SAG table definition for static anycast gateway.
Static anycast gateway HLD [#837](https://github.com/Azure/SONiC/pull/837)

Signed-off-by: Jimi Chen jimi_chen@edge-core.com

### CODE REVIEW

**Review by hasan-brcm — DISMISSED** [review]

**Review by preetham-singh — APPROVED** [review]

**Comment by superchild** [comment]
@preetham-singh @hasan-brcm 
I fix some conflict with the master branch, could you help to review it again? 
Thanks.

**Review by venkatmahalingam — APPROVED** [review]

**Comment by zhangyanzhao** [comment]
Reviewers,
Can you please help to finish the review and merge this PR? I added the maintainers as well who by default will be the reviewer. Thanks.

**Comment by superchild** [comment]
The easyCLA is signed, it should be ready to merge.

**Review by Junchao-Mellanox — APPROVED** [review]

**Comment by zhangyanzhao** [comment]
@superchild  can you please sign the EasyCLA? That is required before the PR merge. Thanks.

**Comment by zhangyanzhao** [comment]
@qiluo-msft  @marian-pritsak  can you please help to merge this PR? It has been approved. Thanks.

**Review by prsunny — APPROVED** [review]

**Pull request merged**
