### PR TITLE
[swig]: Fix swig template memory leak on issue 17025

### PR DESCRIPTION
**Pull request by Pterosaur**
Fix the issue https://github.com/sonic-net/sonic-buildimage/issues/17025 about Redis set activity

Wait PR: https://github.com/sonic-net/sonic-swss-common/pull/836 cherry-pick to 202311

## Description
The issue reports a memory leak on the Redis set operations

## Reason
1. Didn't decrease the reference count after PySequence_GetItem
2. Use the inappropriate Swig API and didn't release the string of SWIG_AsPtr_std_string

## Fix:
1. Refer PR: https://github.com/sonic-net/sonic-swss-common/pull/859 from @praveenraja1
2. Replace the API SWIG_AsPtr_std_string to SWIG_AsVal_std_string

## Add unit test
To monitor there is no dramatic memory increment after a huge amount of Redis set operations.

### CODE REVIEW

**Comment by lguohan** [comment]
@Pterosaur , please check why build failure.

**Comment by Pterosaur** [comment]
> @Pterosaur , please check why build failure.

@lguohan  We should cherry-pick https://github.com/sonic-net/sonic-swss-common/pull/836 to 202311 firstly.

**Comment by Pterosaur** [comment]
@lguohan @qiluo-msft Please help to approve and merge this to 202311

**Comment by keboliu** [comment]
@yxieca would you please help to merge?

**Pull request merged**
