### PR TITLE
[Banner] Added BANNER_MESSAGE table to ConfigDB

### PR DESCRIPTION
**Pull request by SviatoslavBoichuk**
#### Why I did it
Added Banner feature related Config DB table according to HLD: https://github.com/sonic-net/SONiC/pull/1361

#### How I did it
Added Banner table name to schema.h.

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@SviatoslavBoichuk please handle conflict and add to PR description code changes and motivation

**Comment by SviatoslavBoichuk** [comment]
> @SviatoslavBoichuk please handle conflict and add to PR description code changes and motivation

Fixed conflicts, updated PR description

**Review by qiluo-msft — APPROVED** [review]

**Comment by fastiuk** [comment]
@liat-grozovik the checkers finally passed, could you please merge it so I can rerun tests for other repositories?

**Comment by dprital** [comment]
@qiluo-msft , Can you please merge this PR ?

**Pull request merged**
