### PR TITLE
PINS Extension tables support

### PR DESCRIPTION
**Pull request by svshah-intel**
High Level Design: https://github.com/sonic-net/SONiC/pull/1088

This PR is for changes in sonic-swss-common repo
This changes includes, a new #define for tables definition table name in AppDb

Signed-off-by: svshah-intel shitanshu.shah@intel.com

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by zhangyanzhao** [comment]
@prsunny  is this good to be merged?

**Comment by prsunny** [comment]
> @prsunny is this good to be merged?

Done

**Pull request merged**
