### PR TITLE
[dbconnector]: Add API getDbKeys in dbconnector

### PR DESCRIPTION
**Pull request by Pterosaur**
Get a new API `getDbKeys` in dbconnector to fetch all DB keys.

### CODE REVIEW

**Review by ganglyu — DISMISSED** [review]
lgtm

**Comment by ganglyu** [comment]
Need to update swsscommon.i:
%template(VectorSonicDBKey) std::vector<swss::SonicDBKey>;

**Review by ganglyu — APPROVED** [review]

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
