### PR TITLE
Add definition for MEMORY_STATISTICS table in schema

### PR DESCRIPTION
**Pull request by Arham-Nasir**
define table in common/schema.h file of sonic-swss-common

### CODE REVIEW

**Comment by FengPan-Frank** [comment]
LGTM, pls resolve the conflicts.

**Comment by Arham-Nasir** [comment]
> LGTM, pls resolve the conflicts.

@FengPan-Frank , thank you for the review! I checked again. Please let me know if you need any further information.

**Comment by ridahanif96** [comment]
@xincunli-sonic @qiluo-msft @zbud-msft pls help review this PR. All swsscommon/db changes are getting failed since this PR in not Part of master

**Review by ridahanif96 — APPROVED** [review]
Looks good to me , please wait till all checks passes and merge this PR!

**Review by FengPan-Frank — APPROVED** [review]

**Comment by ridahanif96** [comment]
Hi @FengPan-Frank , can you please help merge this PR or get it merged with help of authorized person

**Comment by FengPan-Frank** [comment]
> Hi @FengPan-Frank , can you please help merge this PR or get it merged with help of authorized person

I don't have merge permission, either. pls check with qiluo-msft

**Comment by ridahanif96** [comment]
@qiluo-msft can you please help review this feature and PRs.

**Pull request merged**
