### PR TITLE
Monitor tables for Sirius

### PR DESCRIPTION
**Pull request by siqbal1986**
Added 2 VNET_MONITOR tables. one in APP DB and the other in State DB for Vxlan tunnel endpoint custom monitor.

### CODE REVIEW

**Review by prsunny — APPROVED** [review]

**Comment by qiluo-msft** [comment]
This commit could not be cleanly cherry-picked to 202012. Please submit another PR.

**Comment by prsunny** [comment]
@qiluo-msft , PR is already raised to 202012 and merged. What is the next step? Would you add label "included"?

**Comment by qiluo-msft** [comment]
@prsunny @siqbal1986 
I added the label. I notice 2 issues, you may consider in future:
1. The PR is not 'squash' merge, so there are 2 commits on master branch
2. The 202012 PR has a different title, it is not easy to find and track. Suggest cherry-pick and solve the conflict, and `git commit`. This way the original commit title will be kept.

**Comment by prsunny** [comment]
> @prsunny @siqbal1986 I added the label. I notice 2 issues, you may consider in future:
> 
> 1. The PR is not 'squash' merge, so there are 2 commits on master branch
> 2. The 202012 PR has a different title, it is not easy to find and track. Suggest cherry-pick and solve the conflict, and `git commit`. This way the original commit title will be kept.

Ack

**Comment by siqbal1986** [comment]
sorry about that. Ill make sure that it doesn't happen again.

**Comment by liuh-80** [comment]
@siqbal1986, please also create a submodule PR for 202012 branch, currently the submodule still not update with this change:
https://github.com/sonic-net/sonic-swss-common/tree/fb89310e616ce4a5331aa024a080d70423131131

**Comment by siqbal1986** [comment]
@qiluo-msft can you please CP it to 202211. This needs to be merged for https://github.com/sonic-net/sonic-swss/pull/2738 to get in.

**Comment by StormLiangMS** [comment]
@siqbal1986 cherry-pick failure, pls submit separate PR to 202211.

**Comment by siqbal1986** [comment]
> @siqbal1986 cherry-pick failure, pls submit separate PR to 202211.

Ack

**Pull request merged**
