### PR TITLE
Add field for bulk chunk size in flex counter

### PR DESCRIPTION
**Pull request by stephenxs**
Why I did it
Added a new field in `FLEX_COUNTER_TABLE` to represent the bulk chunk size and bulk chunk size per counter ID for bulk counter polling.

### CODE REVIEW

**Review by liuh-80 — DISMISSED** [review]

**Comment by liuh-80** [comment]
@stephenxs , can you add PR description and check the failed test?

**Review by qiluo-msft — DISMISSED** [review]

**Comment by qiluo-msft** [comment]
Could you link to the HLD PR?

**Review by FengPan-Frank — APPROVED** [review]

**Comment by stephenxs** [comment]
> Could you link to the HLD PR?

https://github.com/sonic-net/SONiC/pull/1864

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
