### PR TITLE
Add docker-mux related table names 

### PR DESCRIPTION
**Pull request by zjswhhh**
This PR is to add table name definitions for database entries used by docker mux processes. 

Sign-off: Jing Zhang zhangjing@microsoft.com

### CODE REVIEW

**Review by yxieca — DISMISSED** [review]

**Review by yxieca — APPROVED** [review]

**Review by lolyu — APPROVED** [review]

**Review by kcudnik — DISMISSED** [review]

**Comment by kcudnik** [comment]
build failure not related to PR

**Comment by zhangyanzhao** [comment]
@zjswhhh would you please check the build failure and merge this PR asap? This is required by 202205

**Comment by zjswhhh** [comment]
> @zjswhhh would you please check the build failure and merge this PR asap? This is required by 202205

Hi @zhangyanzhao  - I have Kamil signed off on this PR, the build failure is not tied to the change. I suspected the failure was introduced by https://github.com/Azure/sonic-swss-common/commit/40a685cd8d72f61c2b7b27ca0e34547ec0876de9. But haven't got a chance to reproduce.

**Review by kcudnik — APPROVED** [review]

**Pull request merged**
