### PR TITLE
[tests] fix binary_data_get unit test

### PR DESCRIPTION
**Pull request by Yakiv-Huryk**
Fix incorrect sizeof() value in the Table.binary_data_get unit test

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@prsunny  can you please merge?

**Comment by prsunny** [comment]
@qiluo-msft to merge

**Comment by Junchao-Mellanox** [comment]
Hi @qiluo-msft ,

This is a blocking issue for bookworm. I see following error in my local build:
```
11:34:33  /usr/include/c++/12/bits/basic_string.h:620:21: error: array subscript 8 is outside array bounds of 'const char [6]' [-Werror=array-bounds]
11:34:33    620 |         _M_construct(__s, __s + __n, std::forward_iterator_tag());
11:34:33        |         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:34:33  In constructor 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]',
11:34:33      inlined from 'virtual void Table_binary_data_get_Test::TestBody()' at tests/redis_ut.cpp:857:53:
11:34:33  /usr/include/c++/12/bits/basic_string.h:620:21: error: array subscript 8 is outside array bounds of 'const char [6]' [-Werror=array-bounds]
11:34:33    620 |         _M_construct(__s, __s + __n, std::forward_iterator_tag());
11:34:33        |         ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

Could you please help merge it if no more comments?

**Review by liuh-80 — APPROVED** [review]

**Pull request merged**
