### PR TITLE
[TWAMP] Add twamp light table to schema

### PR DESCRIPTION
**Pull request by huseratgithub**
[schema][twamp] Add twamp light table to schema

### CODE REVIEW

**Comment by huseratgithub** [comment]
@prsunny PTAL

**Comment by guxianghong** [comment]
@qiluo-msft @arlakshm @rlhui  Could you please help to review and merge this PR, it is depended by  [MR #2927](https://github.com/sonic-net/sonic-swss/pull/2927),  [TWAMP light HLD](https://github.com/sonic-net/SONiC/pull/1320) have been reviewed by the community. Thanks very much.

**Review by prsunny — APPROVED** [review]

**Comment by prsunny** [comment]
@huseratgithub , can you please rebase?

**Comment by huseratgithub** [comment]
> @huseratgithub , can you please rebase?

I have rebase codes to the lastest. PTAL, Thanks.

**Review by arlakshm — APPROVED** [review]

**Comment by prsunny** [comment]
@huseratgithub , you can give '/azpw run'

**Comment by huseratgithub** [comment]
@prsunny @arlakshm Could  you please help to merge?

**Pull request merged**
